### PR TITLE
Add Windows 10/11 exclusive media overlay

### LINKED ISSUE #53: [REQUEST] Media Overlay
This issue was taken from the [osu!player plus issue list](https://github.com/Founntain/osuplayer-issues/issues/31)

**Original Issue below**

I wanna be able to see what is playing without having to alt tab to the music player window but currently whenever I press the keyboard press/play button, no media overlay appears so I can't tell.

Usually on Spotify it would look like this
image

### PR DESCRIPTION
**Pull request by Cesan**
Closes #53

Also technically implements #114 for Windows using the media hotkeys.

https://user-images.githubusercontent.com/33752516/197184125-1f0b9727-9313-445b-864a-90208b1f5495.mp4

### CODE REVIEW

**Review by Founntain — APPROVED** [review]
looks good

**Comment by Cesan** [comment]
tests failing ))

**Comment by Founntain** [comment]
check they need to be green amk

**Comment by Cesan** [comment]
Yes, needed `<EnableWindowsTargeting>true</EnableWindowsTargeting>` to target windows build on other platforms

**Pull request merged**
